version: "3.8"
services:
    db:
      image: mongo:latest
      container_name: albummongodb
      hostname: albummongodb
      environment:
       - PUID=111
       - PGID=111
      volumes:
       - /mongodb/database:/data/db
      ports:
       - 27017:27017
      restart: unless-stopped
      networks:
       - api-net
    api:
      image: albumapi:latest
      container_name: albumtrack
      hostname: albumtrack
      ports:
        - 8080:8080
      depends_on:
       - db
      networks:
        - api-net
      environment:
        - MONGOCONN=mongodb://albummongodb:27017
        - MONGODB=music
        - MONGOCOLLECTION=albums

networks:
  api-net:
    name: api-net
