version: "3.8"

volumes:
  album_data:
    name: albumdb

services:
    db:
      image: mongo:latest
      container_name: albummongo
      hostname: albummongo
      environment:
       - PUID=111
       - PGID=111
      volumes:
       - album_data:/data/albumdb
      ports:
       - 27017:27017
      restart: unless-stopped
      networks:
       - api-net

    api:
      image: albumapi:latest
      container_name: albumtrack
      hostname: albumtrack
      ports:
        - 8080:8080
        - 8081:8081
      depends_on:
       - db
      networks:
        - api-net
      environment:
        - MONGOCONN=mongodb://albummongo:27017
        - MONGODB=music
        - MONGOCOLLECTION=albums
        - CLIENTID=10919655b1da452280cd078457426fd7
        - REDIRECTURI=http://localhost:8080
        - SECRETID=${SPOTIFY_SECRET_ID}

networks:
  api-net:
    name: api-net
