version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
        - PUID=111
        - PGID=111
        volumes:
        - /mongodb/database:/data/db
        ports:
        - 27017:27017
        restart: unless-stopped